package identify

import (
	"embed"
	"encoding/json"
	"fmt"
	"sync"

	"github.com/jumpingmushroom/DiscEcho/daemon/state"
)

// BootCodeEntry is a single game record looked up by its disc-extracted
// identifier. Keys are normalised per system (see ingestion script in
// daemon/identify/data/refresh.go): underscored-dotted for PSX/PS2 boot
// codes (SCES_534.09), uppercase product number for Saturn / Dreamcast
// (MK-81088, MK-51000), uppercase 8-digit hex for Xbox title IDs.
type BootCodeEntry struct {
	Title    string `json:"title"`
	Region   string `json:"region,omitempty"`
	Year     int    `json:"year,omitempty"`
	CoverURL string `json:"cover_url,omitempty"`
}

// BootCodeIndex is a per-system map of disc-extracted identifier to game
// metadata, loaded once at startup from embedded JSON files generated by
// the ingestion script. Reads and writes are both goroutine-safe via the
// RWMutex; in practice MergeFile is only called during startup wiring,
// before the index is shared with handler goroutines.
type BootCodeIndex struct {
	mu       sync.RWMutex
	bySystem map[state.DiscType]map[string]BootCodeEntry
	sources  map[state.DiscType]string // human-readable source label for the Settings tile
}

// bootCodeFile is the on-disk JSON envelope written by the ingestion
// script. The script populates `system` so the loader can sanity-check
// the file matches the discType the caller asked for.
type bootCodeFile struct {
	System    string                   `json:"system"`
	Source    string                   `json:"source"`
	SourceURL string                   `json:"source_url"`
	FetchedAt string                   `json:"fetched_at"`
	Entries   map[string]BootCodeEntry `json:"entries"`
}

// NewBootCodeIndex returns an empty index. Use MergeFile to add per-system data.
func NewBootCodeIndex() *BootCodeIndex {
	return &BootCodeIndex{
		bySystem: make(map[state.DiscType]map[string]BootCodeEntry),
		sources:  make(map[state.DiscType]string),
	}
}

// LoadBootCodeFile parses raw JSON for a single system and returns a
// new BootCodeIndex containing it. Convenience for the single-system case;
// production startup uses LoadAllEmbedded.
func LoadBootCodeFile(system state.DiscType, raw []byte) (*BootCodeIndex, error) {
	idx := NewBootCodeIndex()
	if err := idx.MergeFile(system, raw); err != nil {
		return nil, err
	}
	return idx, nil
}

// MergeFile adds entries from one JSON file under the given system key.
// Returns an error if the file's declared system disagrees with system
// (defensive against loader/file mismatches).
func (idx *BootCodeIndex) MergeFile(system state.DiscType, raw []byte) error {
	var file bootCodeFile
	if err := json.Unmarshal(raw, &file); err != nil {
		return fmt.Errorf("bootcode file: %w", err)
	}
	if string(system) != file.System {
		return fmt.Errorf("bootcode file system mismatch: file says %q, caller asked for %q",
			file.System, system)
	}
	idx.mu.Lock()
	defer idx.mu.Unlock()
	idx.bySystem[system] = file.Entries
	idx.sources[system] = file.Source
	return nil
}

// Lookup returns the entry for a disc-extracted identifier, or nil if
// not indexed. Callers must pass the canonical key form per system.
func (idx *BootCodeIndex) Lookup(system state.DiscType, code string) *BootCodeEntry {
	if idx == nil {
		return nil
	}
	idx.mu.RLock()
	defer idx.mu.RUnlock()
	bucket, ok := idx.bySystem[system]
	if !ok {
		return nil
	}
	entry, ok := bucket[code]
	if !ok {
		return nil
	}
	return &entry
}

// Counts returns per-system entry counts. Used by the Settings System tile
// to show which boot-code maps are loaded.
func (idx *BootCodeIndex) Counts() map[state.DiscType]int {
	if idx == nil {
		return nil
	}
	idx.mu.RLock()
	defer idx.mu.RUnlock()
	out := make(map[state.DiscType]int, len(idx.bySystem))
	for sys, bucket := range idx.bySystem {
		out[sys] = len(bucket)
	}
	return out
}

// Source returns the human-readable source label for a system, e.g.
// "PCSX2 GameIndex.yaml". Empty when no file is loaded for that system.
func (idx *BootCodeIndex) Source(system state.DiscType) string {
	if idx == nil {
		return ""
	}
	idx.mu.RLock()
	defer idx.mu.RUnlock()
	return idx.sources[system]
}

// embeddedFS holds the generated bootcodes_*.json files. The daemon embeds
// them at compile time; the ingestion script (daemon/identify/data/refresh.go)
// regenerates them before each release. bootcodes_placeholder.json satisfies
// the embed glob until Phase 9 generates the real files.
//
//go:embed data/bootcodes_*.json
var embeddedFS embed.FS

// LoadAllEmbedded reads the embedded JSON files and returns a populated
// index. Missing files (e.g. before Phase 9 generates them) are returned
// in the per-system error map; the daemon still starts. Per-system load
// failures degrade auto-id silently; IGDB manual search still works.
func LoadAllEmbedded() (*BootCodeIndex, map[state.DiscType]error) {
	idx := NewBootCodeIndex()
	errs := make(map[state.DiscType]error)
	for _, sys := range []state.DiscType{
		state.DiscTypePSX, state.DiscTypePS2,
		state.DiscTypeSAT, state.DiscTypeDC, state.DiscTypeXBOX,
	} {
		name := fmt.Sprintf("data/bootcodes_%s.json", embeddedFileSuffix(sys))
		raw, err := embeddedFS.ReadFile(name)
		if err != nil {
			errs[sys] = err
			continue
		}
		if err := idx.MergeFile(sys, raw); err != nil {
			errs[sys] = err
		}
	}
	return idx, errs
}

// embeddedFileSuffix maps DiscType to the lowercase suffix used in the
// generated JSON filenames (bootcodes_psx.json etc.).
func embeddedFileSuffix(t state.DiscType) string {
	switch t {
	case state.DiscTypePSX:
		return "psx"
	case state.DiscTypePS2:
		return "ps2"
	case state.DiscTypeSAT:
		return "sat"
	case state.DiscTypeDC:
		return "dc"
	case state.DiscTypeXBOX:
		return "xbox"
	}
	return "unknown"
}
